# tasks/main.yml

- name: Install build tools
  ansible.builtin.dnf:
    name: "@Development tools"
    state: present
  become: yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8) or ansible_distribution == "Amazon"

- name: Install Common useful tools AMAZON Linux 2
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
  - make
  - glibc-devel
  - gcc
  - patch
  - openssl-devel
  - gdb
  # - jansson
  # - tree-sitter
  - emacs
  - unzip
  - tar
  - rsync
  - strace
  - git
  - tmux
  - python-devel
  # - cmake
  # - pkg-config
  # - cmake-data
  - jsoncpp-devel
  - readline-devel
  - llvm-devel
  #- zlib-devel
  when: (ansible_distribution == "Amazon" and ansible_distribution_major_version|int == 2)

- name: Install Common useful tools Amazon 2023
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
  - make
  - glibc-devel
  - gcc
  - clang
  - clang-tools-extra
  - patch
  - openssl-devel
  - gdb
  - emacs
  - unzip
  - tar
  - rsync
  - strace
  - git
  - tmux
  - cmake
  - pkg-config
  - cmake-data
  - jsoncpp-devel
  - readline-devel
  - gtest-devel
  - boost-devel
  # - boost
  - protobuf-devel
  #- zlib-devel
  when: (ansible_distribution == "Amazon" and ansible_distribution_major_version|int == 2023)

- name: Install Common useful tools Centos
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - make
  - glibc-devel
  - gcc
  - patch
  - openssl-devel
  - gdb
  - emacs
  - unzip
  - tar
  - rsync
  - strace
  - git
  - tmux
  - cmake
  # - pkg-config
  # - cmake-data
  - jsoncpp-devel
  - readline-devel
  #- zlib-devel
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8)

- name: Install Common useful tools Ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
  - build-essential
  - autoconf
  # deps for emacs compile -P
  - libgccjit0
  - libgccjit-10-dev
  - libjansson4
  - libjansson-dev
  - gnutls-dev
  - libtree-sitter-dev
  - texinfo
  - zlib1g-dev
  # ----
  - make
  - glibc-source
  - gcc
  - patch
  - openssl
  - libssl-dev
  - gdb
  - emacs
  - unzip
  - tar
  - rsync
  - strace
  - git
  - tmux
  - cmake
  - pkg-config
  - cmake-data
  - libjsoncpp-dev
  - libreadline-dev
  - zlib1g-dev
  - clang
  - clangd
  - libboost-all-dev
#  - libboost1.81-dev
  - libgtest-dev
  - erlang
  when: ansible_distribution == "Ubuntu"

# ATTENTION!
# ubuntu installs jsoncpp into non-standard location
# so add symlinks so cmake find_package could correctly find it
- name: Create symbolic link for jsoncpp
  file:
    src: "/usr/include/jsoncpp/json"
    dest: "/usr/include/json"
    state: link
  when: ansible_distribution == "Ubuntu"
